function Demo(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',_b='.cache.html',_='/',Ub='0F9D1F985E8CFF99F26B5FF9F45D7B4A',Vb='3F0C7935E20C9D6963E31EAE1963E2B7',Wb='7FF7108C48B18F9C895C29DF05EE367C',$b=':',ob='::',hc='<script defer="defer">Demo.onInjectionDone(\'Demo\')<\/script>',hb='<script id="',rb='=',$='?',Xb='B3CC346F9542F278353D4DF5E38B43F1',tb='Bad handler "',Yb='D27D63D2E86F87288AA28BA85AF760BD',gc='DOMContentLoaded',Q='Demo',eb='Demo.nocache.js',nb='Demo::',Zb='F74554CBAC977902DA1FBB7EE716E908',jb='SCRIPT',gb='__gwt_marker_Demo',Cb='android',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Y='end',Ob='gecko',Pb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',ac='gwt/standard/standard.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',fc='head',Sb='hosted.html?Demo',ec='href',Nb='ie6',Mb='ie8',xb='iframe',ab='img',Fb='ipad',Eb='iphone',Db='is_mobile',yb="javascript:''",bc='link',Rb='loadExternalRefs',lb='meta',Bb='mobile.user.agent',Ab='moduleRequested',X='moduleStartup',Lb='msie',mb='name',Gb='not_mobile',Ib='opera',zb='position:absolute;width:0;height:0;border:none',cc='rel',Kb='safari',db='script',Tb='selectingPermutation',R='startup',dc='stylesheet',fb='undefined',Qb='unknown',Hb='user.agent',Jb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}Demo=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Cb)!=-1){return Db}if(a.indexOf(Eb)!=-1){return Db}if(a.indexOf(Fb)!=-1){return Db}return Gb}};u[Bb]={is_mobile:0,not_mobile:1};v[Hb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Ib)!=-1){return Ib}else if(b.indexOf(Jb)!=-1){return Kb}else if(b.indexOf(Lb)!=-1){if(document.documentMode>=8){return Mb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Nb}}}}else if(b.indexOf(Ob)!=-1){return Pb}return Qb};u[Hb]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};Demo.onScriptLoad=function(){if(I){q=true;B()}};Demo.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Rb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Sb;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Tb});if(!A()){try{G([Gb,Pb],Ub);G([Gb,Nb],Vb);G([Gb,Mb],Wb);G([Gb,Kb],Xb);G([Gb,Ib],Yb);G([Db,Kb],Zb);K=w[H(Bb)][H(Hb)];var M=K.indexOf($b);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+_b}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[ac]){var a=m.createElement(bc);__gwt_stylesLoaded[ac]=a;a.setAttribute(cc,dc);a.setAttribute(ec,s+ac);m.getElementsByTagName(fc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(gc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(gc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Rb,millis:(new Date).getTime(),type:T});m.write(hc)}
Demo();